# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/miuicamera

PRODUCT_COPY_FILES += \
    vendor/xiaomi/miuicamera/proprietary/system/etc/default-permissions/miuicamera-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/default-permissions/miuicamera-permissions.xml \
    vendor/xiaomi/miuicamera/proprietary/system/etc/permissions/android.hardware.camera.flash-autofocus.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android.hardware.camera.flash-autofocus.xml \
    vendor/xiaomi/miuicamera/proprietary/system/etc/permissions/android.hardware.camera.front.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android.hardware.camera.front.xml \
    vendor/xiaomi/miuicamera/proprietary/system/etc/permissions/android.hardware.camera.full.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android.hardware.camera.full.xml \
    vendor/xiaomi/miuicamera/proprietary/system/etc/permissions/android.hardware.camera.raw.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android.hardware.camera.raw.xml \
    vendor/xiaomi/miuicamera/proprietary/system/etc/permissions/privapp-permissions-miuicamera.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-miuicamera.xml \
    vendor/xiaomi/miuicamera/proprietary/system/etc/public.libraries-xiaomi.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-xiaomi.txt \
    vendor/xiaomi/miuicamera/proprietary/system/etc/sysconfig/miuicamera-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/miuicamera-hiddenapi-package-whitelist.xml \
    vendor/xiaomi/miuicamera/proprietary/vendor/camera/fonts/FZMiaoWuJW.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/FZMiaoWuJW.ttf \
    vendor/xiaomi/miuicamera/proprietary/vendor/camera/fonts/MFYueYuan-Regular.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/MFYueYuan-Regular.ttf \
    vendor/xiaomi/miuicamera/proprietary/vendor/camera/fonts/MI+LanTing_GB+Outside+YS_V2.3_20160322.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/MI+LanTing_GB+Outside+YS_V2.3_20160322.ttf \
    vendor/xiaomi/miuicamera/proprietary/vendor/camera/fonts/MIUI_Time.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/MIUI_Time.ttf \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/102_SummerDay.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/102_SummerDay.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/103_Fantasy.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/103_Fantasy.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/104_Meet.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/104_Meet.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/105_WindSing.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/105_WindSing.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/106_Lost.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/106_Lost.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/107_Central.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/107_Central.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/108_NorthernEurope.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/108_NorthernEurope.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/109_Rome.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/109_Rome.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/110_BlackGold.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/110_BlackGold.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/111_GreenOrange.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/111_GreenOrange.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/112_Cyberpunk.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/112_Cyberpunk.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/113_BlackIce.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/113_BlackIce.png \
    vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml

PRODUCT_PACKAGES += \
    android.hardware.camera.common_1.0 \
    libMNN \
    libSNPE \
    libarcsoft_single_chart_calibration \
    libauto_crop_c++_shared \
    libautocrop \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libcommon \
    libdoc_photo \
    libdoc_photo_c++_shared \
    libdoc_photo_process \
    libgallery_arcsoft_dualcam_refocus \
    libgallery_arcsoft_portrait_lighting \
    libgallery_arcsoft_portrait_lighting_c \
    libgallery_mpbase \
    libgui_shim_miuicamera \
    libmegvii_bokeh_jni \
    libmialgo_ai_vision \
    libmialgo_autocrop \
    libmialgo_portrait \
    libmialgo_utils_extraphoto \
    libmibokeh_gallery \
    libmibrain_relighting_jni \
    libmicamera_dual_bokeh_jni \
    libmicampostproc_client \
    libmiocr_wrapper \
    libmiphone_bokeh_dynSpot \
    libmiphone_bokeh_effect \
    libmiphone_bokeh_gpf \
    libmiphone_bokeh_proc \
    libmiphone_refocus_bokeh \
    libmisr \
    libmiuiblursdk \
    libmotion_photo \
    libmotion_photo_c++_shared \
    libmotion_photo_mace \
    librefocus \
    librefocus_meitu \
    librefocus_mibokeh \
    libselection \
    libsnpe_dsp_domains_v2 \
    libsymphony-cpu \
    libwa_refocus_extraphoto \
    libxcrash \
    libxcrash_dumper \
    vendor.xiaomi.hardware.campostproc@1.0 \
    vendor.qti.hardware.camera.device@3.5 \
    libmialgo_fs \
    libmialgo_rfs \
    libmialgoengine \
    libswregistrationalgo \
    vendor.qti.hardware.camera.device@1.0 \
    MiuiCamera \
    MiuiExtraPhoto \
    MiuiScanner
